### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by Akiira** [Akiira/MUD-CentralServer#3]
Unless you can think of a reason not to, I'm going to rename this to something like LoginAndStorage server. There are two reasons for this. 
1. In distributed systems central servers are best avoided because they defeat the whole point of being distributed, so even if this is a central server we shouldn't advertise that. 
2. It is not really a central server since all the game logic is handled on the world servers.

**Comment by mixisbad** [comment]
That's fine. I have no objections.
